version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: pizza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: pizza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
  ui:
    build:
      context: ./pushnotif
    ports:
      - "8090:8090"
    depends_on:
      - app